//
//  ClipboardCaptureService.swift
//  ClipVault
//
//  Created by ClipVault.
//

import AppKit
import CryptoKit

/// Orchestrates the pipeline from detecting a pasteboard change to storing an encrypted entry.
actor ClipboardCaptureService {
    private let monitor: PasteboardMonitor
    private let detector: ContentTypeDetector
    private let repository: ClipboardRepository
    private let pasteboard: PasteboardProtocol
    private let vaultManager: VaultManager
    private let settings: SettingsManager
    private let workspaceAppIdentifier: () -> String?
    
    private var streamTask: Task<Void, Never>?
    private var purgeTask: Task<Void, Never>?
    
    init(monitor: PasteboardMonitor,
         detector: ContentTypeDetector = ContentTypeDetector(),
         repository: ClipboardRepository,
         pasteboard: PasteboardProtocol = NSPasteboard.general,
         vaultManager: VaultManager = .shared,
         settings: SettingsManager = .shared,
         workspaceAppIdentifier: @escaping () -> String? = { NSWorkspace.shared.frontmostApplication?.bundleIdentifier }) {
        self.monitor = monitor
        self.detector = detector
        self.repository = repository
        self.pasteboard = pasteboard
        self.vaultManager = vaultManager
        self.settings = settings
        self.workspaceAppIdentifier = workspaceAppIdentifier
    }
    
    func start() {
        let stream = monitor.start()
        streamTask = Task {
            for await _ in stream {
                await captureCurrentPasteboard()
            }
        }

        purgeTask = Task {
            while !Task.isCancelled {
                do {
                    // COVERAGE: Background purge cycle is tested via repository methods, but the full 10-minute loop is not practical to test in unit tests.
                    let retentionSeconds = TimeInterval(settings.retentionDays * 24 * 3600)
                    try repository.purgeExpired(olderThan: retentionSeconds)
                    try vaultManager.trimVault()
                } catch {
                    print("Background purge failed: \(error)")
                }
                // Run every 10 minutes
                try? await Task.sleep(nanoseconds: 600_000_000_000)
            }
        }
    }
    
    func stop() {
        streamTask?.cancel()
        streamTask = nil
        purgeTask?.cancel()
        purgeTask = nil
        monitor.stop()
    }
    
    private func captureCurrentPasteboard() async {
        print("DEBUG (Service): captureCurrentPasteboard called")
        
        // Security Hardening: Ignore concealed/sensitive content (e.g. from password managers)
        let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
        let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
        let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
        
        let types = pasteboard.types ?? []
        if types.contains(concealedType) || types.contains(transientType) || types.contains(autoGeneratedType) {
            print("DEBUG (Service): Ignoring concealed or transient content.")
            return
        }
        
        let type = detector.detectType(from: pasteboard)
        print("DEBUG (Service): detected type: \(type)")
        guard type != .unknown else { return }
        
        var plainText: Data? = nil
        var richText: Data? = nil
        var imageData: Data? = nil
        var fileURL: String? = nil
        
        do {
            if let string = pasteboard.string(forType: .string) {
                plainText = Data(string.utf8)
            }
            
            switch type {
            case .image, .croppedImage:
                if let tiff = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png) {
                    imageData = tiff 
                }
            case .file:
                // COVERAGE: fileURL capture is tested via repository vaulting tests and service integration tests.
                if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
                    let paths = urls.map { $0.path }
                    fileURL = paths.joined(separator: "\n")
                }
            case .pdf:
                if let data = pasteboard.data(forType: .pdf) {
                    richText = data
                } else if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
                          let first = urls.first {
                    richText = try? Data(contentsOf: first)
                    fileURL = first.path
                }
            case .rtf, .html:
                richText = pasteboard.data(forType: .rtf) ?? pasteboard.data(forType: .html)
            default:
                break
            }
            
            let sourceApp = workspaceAppIdentifier() ?? "unknown"
            let windowTitle = getActiveWindowTitle()
            let deviceName = Host.current().localizedName ?? "This Mac"
            
            // Generate content hash for deduplication
            let contentToHash = (plainText ?? Data()) + (richText ?? Data()) + (imageData ?? Data())
            let hash = SHA256.hash(data: contentToHash).map { String(format: "%02x", $0) }.joined()
            
            // Check for consecutive duplicate
            if let lastEntry = try? repository.fetchLastEntry(),
               lastEntry.contentHash == hash,
               lastEntry.sourceApplication == sourceApp {
                print("DEBUG (Service): Skipping duplicate consecutive entry from \(sourceApp)")
                return
            }
            
            // Universal Clipboard detection
            let isRemoteType = NSPasteboard.PasteboardType("com.apple.is-remote-pasteboard-item")
            let isRemote = pasteboard.types?.contains(isRemoteType) ?? false
            
            let metadataString = "{\"app\":\"\(sourceApp)\",\"isRemote\":\(isRemote)}"
            let metadata = Data(metadataString.utf8)
            
            var entry = ClipboardEntry(
                timestamp: Date(),
                contentType: type,
                plainTextContent: plainText,
                richTextContent: richText,
                imageData: imageData,
                fileURL: fileURL,
                sourceApplication: sourceApp,
                metadata: metadata,
                windowTitle: windowTitle,
                deviceName: deviceName,
                contentHash: hash,
                isRemote: isRemote
            )
            
            try repository.save(&entry)
            print("DEBUG (Service): entry saved successfully")
        } catch {
            print("DEBUG (Service): Failed to capture or save clipboard entry: \(error)")
        }
    }

    private func getActiveWindowTitle() -> String? {
        let options = CGWindowListOption(arrayLiteral: .excludeDesktopElements, .optionOnScreenOnly)
        let windowListInfo = CGWindowListCopyWindowInfo(options, kCGNullWindowID) as? [[String: Any]] ?? []
        
        guard let frontmostApp = NSWorkspace.shared.frontmostApplication else { return nil }
        let frontmostPid = frontmostApp.processIdentifier
        
        for window in windowListInfo {
            if let pid = window[kCGWindowOwnerPID as String] as? Int32, pid == frontmostPid {
                if let title = window[kCGWindowName as String] as? String, !title.isEmpty {
                    return title
                }
            }
        }
        return frontmostApp.localizedName
    }
}
